stages:
  - install

job1:
  tags:
    - aa
  stage: install
  script:
    - file my-file
    - echo $RANDOM >> my-file
    - file my-file
    - cat my-file

job2:
  tags:
    - aa
  stage: install
  script:
    - file my-file
    - echo $RANDOM >> my-file
    - file my-file
    - cat my-file
