stages:
  - install

job1:
  tags:
    - aa
  stage: install
  script:
    - file my-file
    - echo $RANDOM >> my-file
    - file my-file
    - cat my-file
  cache:
    key: file1
    paths:
      - my-file

job2:
  tags:
    - aa
  stage: install
  script:
    - file my-file
    - echo $RANDOM >> my-file
    - file my-file
    - cat my-file
