stages:
  - install
  - test

job1:
  tags:
    - aa
  stage: install
  script:
    - echo $RANDOM >> my-file
    - cat my-file
  artifacts:
    name: my-files
    paths:
      - my-file

job2:
  tags:
    - aa
  stage: test
  script:
    - cat my-file
