stages:
  - install

job1:
  # tags:
  #   - gitlab11-shell # 需要有设置 Run untagged jobs 的 runner 来运行无 tag 的 job
  stage: install
  script:
    - echo $RANDOM >> /my-file-gitlab11
    - cat /my-file-gitlab11
